name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Exercise
        id: exercise
        uses: ./
        with:
          ref: v1.0.0

      - name: Verify
        env:
          REF: ${{ steps.exercise.outputs.ref }}
          COMMIT: ${{ steps.exercise.outputs.commit }}
        run: |
          set -x
          test "${REF}" = "v1.0.0"
          test "${COMMIT}" = "9dc5e35df968226e7707f49ddbf4f4af6028caa4"
