name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Exercise
        id: exercise
        uses: ./
        with:
          ref: feb0b063fb6f4731a5a6db8a5d94e7163bf460dc

      - name: Verify
        env:
          REF: ${{ steps.exercise.outputs.ref }}
          COMMIT: ${{ steps.exercise.outputs.commit }}
        run: |
          set -x
          test "${REF}" = ""
          test "${COMMIT}" = "feb0b063fb6f4731a5a6db8a5d94e7163bf460dc"
